### PR TITLE
add PR number (GH relative ID)

### PR DESCRIPTION
**Pull request by Hades32**
Change-type: patch
Signed-off-by: Martin Rauscher <martin@balena.io>

### CODE REVIEW

**Comment by Hades32** [comment]
@balena-ci I self-certify!

**Comment by Hades32** [comment]
@balena-ci retest

**Comment by Hades32** [comment]
@balena-ci retest

**Comment by codewithcheese** [comment]
@balena-ci retest

**Comment by Hades32** [comment]
probably fails because we're waiting for https://github.com/product-os/jellyfish-plugin-github/pull/612

**Comment by Hades32** [comment]
@balena-ci rebase

**Pull request merged**
