### PR TITLE
Don't prefix the org name on repository names

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Change-type: patch
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by joshbwlng** [comment]
@LucianBuzzo Do we need to update repository contracts we already have in the production db?

**Comment by LucianBuzzo** [comment]
Yep, though this can be done pretty easily with a script and the SDK

**Comment by LucianBuzzo** [comment]
@balena-ci rebase

**Comment by LucianBuzzo** [comment]
@balena-ci rebase

**Comment by LucianBuzzo** [comment]
@balena-ci I self-certify!

**Pull request merged**
